apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medinsights

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: patient-service
    count: 3  # Higher replica count for production

images:
  - name: patient-service
    newName: your-registry.io/medinsights/patient-service  # Replace with your registry
    newTag: v0.0.1

patchesStrategicMerge:
  - deployment-patch.yaml
