apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medinsights

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: patient-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: medinsights

images:
  - name: patient-service
    newName: patient-service  # Replace with: your-registry.io/medinsights/patient-service
    newTag: latest
