apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medinsights-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: patient-service
    newTag: dev-latest
